#!/bin/bash

tempfile="$(mktemp)"

write_pid () {
	$(echo "$1 " >> "$tempfile")
}

read_pids () {
	echo $(cat "$tempfile")
}

clear_pids () {
	for i in $(cat "$tempfile"); do
		kill -9 ${i} &> /dev/null
	done
	echo > "$tempfile"
}

run_procs_s () {
	if (( $# > 0)); then
		$1 &
		write_pid $!;
		if wait $! &> /dev/null; then 
			shift
			run_procs_s "$@" &
		fi
	fi
}

dispose () {
	clear_pids
	echo -en "\nBye"
	rm "$tempfile"
	exit
}

execute () {
	clear_pids
	run_procs_s "npx tsc --build --verbose" "node build"
}


trap dispose SIGINT

execute
while true; do
	inotifywait -e modify -r src &> /dev/null
	execute
done

# TODO create /dev/shm build directory to reduce disk usage
# TODO create ENV to store variable info about build
